import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🔄 Sinkronisasi produk Free Fire...");

  /*
   * Produk lama tidak dihapus karena mungkin sudah terhubung
   * dengan histori Order. Produk yang tidak ada dalam daftar
   * di bawah akan dinonaktifkan.
   */
  await prisma.product.updateMany({
    where: {
      game: "Free Fire",
    },
    data: {
      active: false,
    },
  });

  const products = [
    {
      game: "Free Fire",
      name: "5 Diamond",
      sku: "FF5",
      providerCode: "ff5",
      price: 750,
      providerPrice: 750,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "10 Diamond",
      sku: "FF10",
      providerCode: "ff10",
      price: 1525,
      providerPrice: 1525,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "12 Diamond",
      sku: "FF12",
      providerCode: "ff12",
      price: 1615,
      providerPrice: 1615,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "20 Diamond",
      sku: "FF20",
      providerCode: "ff20",
      price: 3041,
      providerPrice: 3041,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "25 Diamond",
      sku: "FF25",
      providerCode: "ff25",
      price: 3800,
      providerPrice: 3800,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "30 Diamond",
      sku: "FF30",
      providerCode: "ff30",
      price: 4559,
      providerPrice: 4559,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "40 Diamond",
      sku: "FF40",
      providerCode: "ff40",
      price: 5786,
      providerPrice: 5786,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "50 Diamond",
      sku: "FF50",
      providerCode: "ff50",
      price: 4980,
      providerPrice: 4980,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "55 Diamond",
      sku: "FF55",
      providerCode: "ff55",
      price: 6775,
      providerPrice: 6775,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "70 Diamond",
      sku: "FF70",
      providerCode: "ff70",
      price: 7000,
      providerPrice: 7000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "75 Diamond",
      sku: "FF75",
      providerCode: "ff75",
      price: 6000,
      providerPrice: 6000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "80 Diamond",
      sku: "FF80",
      providerCode: "ff80",
      price: 6000,
      providerPrice: 6000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "90 Diamond",
      sku: "FF90",
      providerCode: "ff90",
      price: 6500,
      providerPrice: 6500,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "100 Diamond",
      sku: "FF100",
      providerCode: "ff100",
      price: 12020,
      providerPrice: 12020,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "120 Diamond",
      sku: "FF120",
      providerCode: "ff120",
      price: 8200,
      providerPrice: 8200,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "140 Diamond",
      sku: "FF140",
      providerCode: "ff140",
      price: 11000,
      providerPrice: 11000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "145 Diamond",
      sku: "FF145",
      providerCode: "ff145",
      price: 16000,
      providerPrice: 16000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "150 Diamond",
      sku: "FF150",
      providerCode: "ff150",
      price: 13000,
      providerPrice: 13000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "160 Diamond",
      sku: "FF160",
      providerCode: "ff160",
      price: 9500,
      providerPrice: 9500,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "170 Diamond",
      sku: "FF170",
      providerCode: "ff170",
      price: 16000,
      providerPrice: 16000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "190 Diamond",
      sku: "FF190",
      providerCode: "ff190",
      price: 12000,
      providerPrice: 12000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "200 Diamond",
      sku: "FF200",
      providerCode: "ff200",
      price: 24344,
      providerPrice: 24344,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "210 Diamond",
      sku: "FF210",
      providerCode: "ff210",
      price: 24860,
      providerPrice: 24860,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "250 Diamond",
      sku: "FF250",
      providerCode: "ff250",
      price: 20000,
      providerPrice: 20000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "280 Diamond",
      sku: "FF280",
      providerCode: "ff280",
      price: 18725,
      providerPrice: 18725,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "300 Diamond",
      sku: "FF300",
      providerCode: "ff300",
      price: 36641,
      providerPrice: 36641,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "355 Diamond",
      sku: "FF355",
      providerCode: "ff355",
      price: 28500,
      providerPrice: 28500,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "375 Diamond",
      sku: "FF375",
      providerCode: "ff375",
      price: 35000,
      providerPrice: 35000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "400 Diamond",
      sku: "FF400",
      providerCode: "ff400",
      price: 48040,
      providerPrice: 48040,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "405 Diamond",
      sku: "FF405",
      providerCode: "ff405",
      price: 39000,
      providerPrice: 39000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "425 Diamond",
      sku: "FF425",
      providerCode: "ff425",
      price: 41000,
      providerPrice: 41000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "475 Diamond",
      sku: "FF475",
      providerCode: "ff475",
      price: 44000,
      providerPrice: 44000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "495 Diamond",
      sku: "FF495",
      providerCode: "ff495",
      price: 50000,
      providerPrice: 50000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "500 Diamond",
      sku: "FF500",
      providerCode: "ff500",
      price: 59374,
      providerPrice: 59374,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "510 Diamond",
      sku: "FF510",
      providerCode: "ff510",
      price: 50000,
      providerPrice: 50000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "545 Diamond",
      sku: "FF545",
      providerCode: "ff545",
      price: 54525,
      providerPrice: 54525,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "565 Diamond",
      sku: "FF565",
      providerCode: "ff565",
      price: 54000,
      providerPrice: 54000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "635 Diamond",
      sku: "FF635",
      providerCode: "ff635",
      price: 64000,
      providerPrice: 64000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "720 Diamond",
      sku: "FF720",
      providerCode: "ff720",
      price: 83175,
      providerPrice: 83175,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "725 Diamond",
      sku: "FF725",
      providerCode: "ff725",
      price: 77000,
      providerPrice: 77000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "740 Diamond",
      sku: "FF740",
      providerCode: "ff740",
      price: 82025,
      providerPrice: 82025,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "770 Diamond",
      sku: "FF770",
      providerCode: "ff770",
      price: 76000,
      providerPrice: 76000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "790 Diamond",
      sku: "FF790",
      providerCode: "ff790",
      price: 79025,
      providerPrice: 79025,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "860 Diamond",
      sku: "FF860",
      providerCode: "ff860",
      price: 88000,
      providerPrice: 88000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "930 Diamond",
      sku: "FF930",
      providerCode: "ff930",
      price: 92525,
      providerPrice: 92525,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "1000 Diamond",
      sku: "FF1000",
      providerCode: "ff1000",
      price: 117345,
      providerPrice: 117345,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "1075 Diamond",
      sku: "FF1075",
      providerCode: "ff1075",
      price: 110025,
      providerPrice: 110025,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "1440 Diamond",
      sku: "FF1440",
      providerCode: "ff1440",
      price: 158000,
      providerPrice: 158000,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "1450 Diamond",
      sku: "FF1450",
      providerCode: "ff1450",
      price: 156025,
      providerPrice: 156025,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "2000 Diamond",
      sku: "FF2000",
      providerCode: "ff2000",
      price: 232850,
      providerPrice: 232850,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "2160 Diamond",
      sku: "FF2160",
      providerCode: "ff2160",
      price: 250813,
      providerPrice: 250813,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "2180 Diamond",
      sku: "FF2180",
      providerCode: "ff2180",
      price: 234025,
      providerPrice: 234025,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "2355 Diamond",
      sku: "FF2355",
      providerCode: "ff2355",
      price: 272406,
      providerPrice: 272406,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "2720 Diamond",
      sku: "FF2720",
      providerCode: "ff2720",
      price: 315268,
      providerPrice: 315268,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "3640 Diamond",
      sku: "FF3640",
      providerCode: "ff3640",
      price: 417515,
      providerPrice: 417515,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "4000 Diamond",
      sku: "FF4000",
      providerCode: "ff4000",
      price: 461134,
      providerPrice: 461134,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "7290 Diamond",
      sku: "FF7290",
      providerCode: "ff7290",
      price: 836531,
      providerPrice: 836531,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "Membership Mingguan",
      sku: "FF_MEMBERSHIP_WEEKLY",
      providerCode: "FF_ID_MM",
      price: 26000,
      providerPrice: 25365,
      popular: false,
      active: true,
    },
    {
      game: "Free Fire",
      name: "Membership Bulanan",
      sku: "FF_MEMBERSHIP_MONTHLY",
      providerCode: "FF_ID_MB",
      price: 77000,
      providerPrice: 76045,
      popular: false,
      active: true,
    },
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: {
        sku: product.sku,
      },
      update: {
        game: product.game,
        name: product.name,
        providerCode: product.providerCode,
        price: product.price,
        providerPrice: product.providerPrice,
        popular: product.popular,
        active: product.active,
      },
      create: product,
    });

    console.log(
      `✅ ${product.name} | ${product.providerCode} | Rp${product.price.toLocaleString(
        "id-ID",
      )}`,
    );
  }

  console.log("");
  console.log(`✅ ${products.length} produk Free Fire aktif.`);
  console.log("✅ Histori order lama tetap aman.");
}

main()
  .catch((error) => {
    console.error("❌ Seeder gagal:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
